name: test_sqlite_drift
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:

  cupertino_icons: ^1.0.2
  drift: ^2.2.0

  flutter:
    sdk: flutter

  intl: ^0.17.0
  path: ^1.8.2
  path_provider: ^2.0.11
  provider: ^6.0.4
  sqlite3_flutter_libs: ^0.5.11+1

dev_dependencies:

  build_runner: ^2.3.2
  drift_dev: ^2.2.0+1

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
